### ISSUE TITLE
Handling of hyphenated words and period delineated acronyms, backticks (other punctuations)?

### ISSUE THREAD

**Issue by r3wt** [Gumball12/bionic-reading#18]
Hi gumball, I'm back home from my surgery and decided to push the bionic api a bit more and see what i could discover about how it handles edge cases. here is a screenshot

![image](https://user-images.githubusercontent.com/4483325/170782290-253213ab-0adc-434e-ad51-7311b53ad1c9.png)

As you can see the roman numerals and numeric lists will require no special logic to support, and indeed your algorithm already will match the bionic api for this, so thats good.

But i identified two edge cases:

1. period delineated acronyms - like the `S.W.A.T` in the above screen. As you can see their api identifies it as an a single word and ignores the periods for purposes of word highlighting, but also periods in the highlighted section are highlighted as well. this might require a bit of tricky logic, i am not sure. maybe you can think of a better solution
2. hyphenated words - like `github-api` in above example. as you can see each segment of a hyphenated word grouping is highlighted seperately. 

Also, noticed that backtick and possibly other punctuation characters need to be ignored like you've already done with periods and such, so perhaps we need to look deeper into that to add full support for all punctuation characters. 

If i can think of any other odd edge cases, i will report back to this thread.

**Comment by Gumball12** [comment]
@r3wt 
Thanks again for the helpful feedback! I will investigate the mentioned edge cases and fix them soon.

\+
So, you're saying that the logic of the current Bionic-Reading (BR) NPM module is the same as the actual BR API, but there is an edge case that looks strange in both of them, right?

**Comment by Gumball12** [comment]
Hi. It's me again.

In the [v1.5.0](https://github.com/Gumball12/text-vide/releases/tag/v1.5.0), I changed the target of the project a little. Previously, the purpose was to do the same thing as the Bionic-Reading API, but I didn't think it was necessary for some reasons. (That doesn't mean much of a difference. See [How.md](https://github.com/Gumball12/text-vide/blob/main/HOW.md) for details.)

I think this issue is related to the edge case for Bionic-Reading API. So... I'll close this issue.
If you don't think so, open it again anytime, or create a new issue.

Thank you for your interest in this module.
