### ISSUE TITLE
Question: Possible highlighting of root-words

### ISSUE THREAD

**Issue by KyahWill** [Gumball12/bionic-reading#29]
Do you think it would be a lot more efficient if we try to highlight the root words if deemed necessary?

**Comment by Gumball12** [comment]
Hi. Thanks for leaving a question.

The goal of this project is to implement Bionic-Reading as an NPM module. So I didn't think of anything like highlighting a certain part of a word.

I hope the answer is helpful. Thank you.

**Comment by Gumball12** [comment]
Hi. It's me again.
In this [v1.5.0](https://github.com/Gumball12/text-vide/releases/tag/v1.5.0), I changed the target of the project a little. Previously, the purpose was to do the same thing as the Bionic-Reading API, but I didn't think it was necessary for some reasons. So I think you might consider what you suggested.

But I don't want the performance to go down or the size of the bundled file to get bigger due to other dependencies. So I'm not sure how to implement what you said. If you have any ideas, please tell me.

Perhaps this comment answered. If you have any questions, please leave a new issue or leave another comment.
Thank you.
